### ISSUE TITLE
Apache Camel integration

### ISSUE THREAD

**Issue by tsarenkotxt** [Nike-Inc/backstopper#45]
How to integrate with the [Apache Camel](https://camel.apache.org/) and Spring Boot 2(REST DSL)?

**Comment by nicmunroe** [comment]
Hi @tsarenkotxt - sorry for missing this issue before. Have you tried the new Backstopper+Springboot 2 support? Specifically the [backstopper-spring-boot2-webmvc](https://github.com/Nike-Inc/backstopper/tree/master/backstopper-spring-boot2-webmvc) and [backstopper-spring-web-flux](https://github.com/Nike-Inc/backstopper/tree/master/backstopper-spring-web-flux) modules (depending on whether your SB2 app is servlet-based or project reactor based).

That will integrate backstopper into SB2. If the apache camel stuff uses SB2's error handling mechanisms, then it should work without any further effort. But if it bypasses SB2's error handling in favor of its uses its own error handling system then you're out of luck. 

I haven't used this specific combination (camel rest DSL+SB2) so I can't say for sure, but🤞 that simply adding the core Backstopper+SB2 integration will cause things to work.

**Comment by nicmunroe** [comment]
I'm closing this because I believe the new Backstopper+Springboot 2 modules likely cover this use case. If they don't, feel free to reopen the issue with more details (preferably a minimal Camel+SB2 project that could be used as a testbed).
